version: '3.8'

services:
  db:
    image: postgres:15
    container_name: bank_t1_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: bank_t1
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_net

  app:
    build: .
    container_name: bank_t1_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:

      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bank_t1
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root

      SPRING_LIQUIBASE_ENABLED: "true"
    networks:
      - app_net

volumes:
  db_data:

networks:
  app_net:
    driver: bridge
