spring:
  datasource:
    url: jdbc:postgresql://db:5432/bank_t1
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml

# Logging
logging:
  level:
    root: INFO
    ru.t1.homework: DEBUG
    org.springframework.web: INFO
