server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/kafka_example
    username: kafkaUser
    password: kafkaPassword
  jpa:
    hibernate:
      ddl-auto: update

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.oauth2.client.OAuth2ClientAutoConfiguration

  cloud:
    openfeign:
      oauth2:
        enabled: false

  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

security:
  jwt:
    secret: my-super-secret-key-that-nobody-else-knows-123456
    expiration-ms: 3600000

service2:
  url: http://service2:8081

transactions:
  reject:
    threshold: 10
